### ISSUE TITLE
.getCalls() throw expection for non-english fritzbox ui

### ISSUE THREAD

**Issue by fabianfetting** [lesander/fritzbox.js#4]
The request of .getCalls() throws an expection for non-english fritzbox user interfaces (format.js:22).

The naming of the csv file topics for german ui is:
Typ;Datum;Name;Rufnummer;Nebenstelle;Eigene Rufnummer;Dauer

**Comment by lesander** [comment]
Thank you for catching this. I'll address this in v2.

**Comment by lesander** [comment]
Hi Fabian, Could you please share the full stack trace and exception you encountered?

**Comment by fabianfetting** [comment]
No problem, here is the stack trace:
```
TypeError: Cannot read property 'replace' of undefined
    at Object.fritzFormat.callType (/Users/fabian/git/fritzbox.js-bug/node_modules/fritzbox.js/src/format.js:80:10)
    at Object.fritzFormat.calls (/Users/fabian/git/fritzbox.js-bug/node_modules/fritzbox.js/src/format.js:22:25)
    at fritzLogin.getSessionId.then.then.then.then (/Users/fabian/git/fritzbox.js-bug/node_modules/fritzbox.js/src/fon.js:40:34)
    at <anonymous>
```

**Comment by lesander** [comment]
@fur6y Could you please check if the proposed fix in `2.0.0` resolves your issue?

**Comment by fabianfetting** [comment]
I've tested it and it works perfectly. Thx.

**Comment by lesander** [comment]
Great! Thank you for reporting. If you stumble across anything else please let me know 😄
